export default [
  'Vacuous Company',
  'Quick Zinc',
  'Detailed Selection',
  'Flat Chalk',
  'Waiting Yak',
  'Purple Push',
  'Tense Mint',
  'Unequal Drink',
  'Thinkable Line',
  'Remarkable Tank',
  'Blow Vessel',
  'Profit Industry',
  'Test Smoke',
  'Sofa Argument Industry',
  'Bears Coach',
  'Stomach Mark Industries',
  'Iron Oven',
  'Idea Cactus',
  'Interest Vase Cactus',
  'Toy Dad Cactus',
  'Prescribe Elbow Cactus',
  'Worry Debt Cactus',
  'Surround Salt Cactus',
  'Head Breakfast Cactus',
  'Own Wire',
  'Generate Ring',
  'Generater Ring',
  'Greet Bun',
];